### ISSUE TITLE
When producer throws, the exception is only thrown on the creating thread, all other threads hang

### ISSUE THREAD

**Issue by extremeandy** [Aaronontheweb/FastAtomicLazy#12]
**Describe the bug**
If the producer throws an exception on the creating thread, only the creating thread receives the exception, all other threads hang.

**To Reproduce**
Run this test case:

```csharp
[Fact]
public void FastLazy_AllThreads_ShouldThrowException_WhenFactoryThrowsException()
{
	var lazy = new FastLazy<string>(() => throw new Exception("Factory exception"));
	var result = Parallel.For(0, Environment.ProcessorCount, i =>
	{
		Assert.Throws<Exception>(() => _ = lazy.Value);
	});
	SpinWait.SpinUntil(() => result.IsCompleted);
}
```

**Expected behavior**
Accessing `Value` should throw an exception if the factory throws an exception on *all* threads.

**Actual behavior**
FastLazy hangs internally on `SpinWait.SpinUntil(...)`

**Additional context**
Happy to provide my solution if you're curious.

**Comment by Aaronontheweb** [comment]
> Happy to provide my solution if you're curious.

that would be great

**Comment by extremeandy** [comment]
I really should have posted it at the time... I don't have access to that code any more sorry, I've moved on from that company!
