### ISSUE TITLE
Atomicity issue

### ISSUE THREAD

**Issue by Rattenkrieg** [Aaronontheweb/FastAtomicLazy#2]
Consider [this line](https://github.com/Aaronontheweb/FastAtomicLazy/blob/master/FastAtomicLazy/FastLazy.cs#L51) or to be precise _the moment_ when `!IsValueCreationInProgress()` have been executed and we're stepping into _then_ branch but before `Volatile.Write(ref _creating, 1);` is executed. Thread may be preempted here. Possibilities are negligible but it can happen anyway. Just insert `Thread.Yield();` before `Volatile.Write(ref _creating, 1);` and see failing specs. Solution is to use `Interlocked.CompareExchange(ref _creating, 1, 0) == 0`.

**Comment by Aaronontheweb** [comment]
Thanks for this @Rattenkrieg - I failed to follow up on this for some reason

**Comment by Aaronontheweb** [comment]
Closed by #3
