### ISSUE TITLE
Release producer after value has been produced

### ISSUE THREAD

**Issue by extremeandy** [Aaronontheweb/FastAtomicLazy#7]
**Is your feature request related to a problem? Please describe.**
No problem, just a suggestion.

**Describe the solution you'd like**
Set `_producer` to `null` once a value has been produced, so that GC can clean-up any resources related to the Func<T>. See the Microsoft Lazy<T> implementation, which gave me the idea.

**Comment by Aaronontheweb** [comment]
That's a good idea
